export const COMPANY_PAGE_DATA_REQUEST = 'COMPANY_PAGE_DATA_REQUEST'
export const COMPANY_PAGE_DATA_SUCCESS = 'COMPANY_PAGE_DATA_SUCCESS'
export const COMPANY_PAGE_DATA_FAIL = 'COMPANY_PAGE_DATA_FAIL'

export const COMPANIES_DATA_REQUEST = "COMPANIES_DATA_REQUEST"
export const COMPANIES_DATA_SUCCESS = "COMPANIES_DATA_SUCCESS"
export const COMPANIES_DATA_FAIL = "COMPANIES_DATA_FAIL"

export const COMPANY_EDIT_REQUEST = 'COMPANY_EDIT_REQUEST'
export const COMPANY_EDIT_SUCCESS = 'COMPANY_EDIT_SUCCESS'
export const COMPANY_EDIT_FAIL = 'COMPANY_EDIT_FAIL'

export const COMPANY_DELETE_REQUEST = 'COMPANY_DELETE_REQUEST'
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS'
export const COMPANY_DELETE_FAIL = 'COMPANY_DELETE_FAIL'

export const COMPANY_EDITOR_LIST_REQUEST = 'COMPANY_EDITOR_LIST_REQUEST'
export const COMPANY_EDITOR_LIST_SUCCESS = 'COMPANY_EDITOR_LIST_SUCCESS'
export const COMPANY_EDITOR_LIST_FAIL = 'COMPANY_EDITOR_LIST_FAIL'

export const COMPANY_EDITOR_DELETE_REQUEST = 'COMPANY_EDITOR_DELETE_REQUEST'
export const COMPANY_EDITOR_DELETE_SUCCESS = 'COMPANY_EDITOR_DELETE_SUCCESS'
export const COMPANY_EDITOR_DELETE_FAIL = 'COMPANY_EDITOR_DELETE_FAIL'

