export const COMPANY_PAGE_DATA_REQUEST = 'COMPANY_PAGE_DATA_REQUEST'
export const COMPANY_PAGE_DATA_SUCCESS = 'COMPANY_PAGE_DATA_SUCCESS'
export const COMPANY_PAGE_DATA_FAIL = 'COMPANY_PAGE_DATA_FAIL'