export const HOMEPAGE_CARDS_REQUEST = 'HOMEPAGE_CARDS_REQUEST'
export const HOMEPAGE_CARDS_SUCCESS = 'HOMEPAGE_CARDS_SUCCESS'
export const HOMEPAGE_CARDS_FAIL = 'HOMEPAGE_CARDS_FAIL'

export const HOMEPAGE_CARD_REQUEST = 'HOMEPAGE_CARD_REQUEST'
export const HOMEPAGE_CARD_SUCCESS = 'HOMEPAGE_CARD_SUCCESS'
export const HOMEPAGE_CARD_FAIL = 'HOMEPAGE_CARD_FAIL'

export const HOMEPAGE_CARDS_DELETE_REQUEST = 'HOMEPAGE_CARDS_DELETE_REQUEST'
export const HOMEPAGE_CARDS_DELETE_SUCCESS = 'HOMEPAGE_CARDS_DELETE_SUCCESS'
export const HOMEPAGE_CARDS_DELETE_FAIL = 'HOMEPAGE_CARDS_DELETE_FAIL'

export const HOMEPAGE_CARD_ADD_REQUEST = 'HOMEPAGE_CARD_ADD_REQUEST'
export const HOMEPAGE_CARD_ADD_SUCCESS = 'HOMEPAGE_CARD_ADD_SUCCESS'
export const HOMEPAGE_CARD_ADD_FAIL = 'HOMEPAGE_CARD_ADD_FAIL'

export const HOMEPAGE_CARD_EDIT_REQUEST = 'HOMEPAGE_CARD_EDIT_REQUEST'
export const HOMEPAGE_CARD_EDIT_SUCCESS = 'HOMEPAGE_CARD_EDIT_SUCCESS'
export const HOMEPAGE_CARD_EDIT_FAIL = 'HOMEPAGE_CARD_EDIT_FAIL'