export const HOMEPAGE_CARDS_REQUEST = 'HOMEPAGE_CARDS_REQUEST'
export const HOMEPAGE_CARDS_SUCCESS = 'HOMEPAGE_CARDS_SUCCESS'
export const HOMEPAGE_CARDS_FAIL = 'HOMEPAGE_CARDS_FAIL'

export const HOMEPAGE_GET_ALL_CARDS_REQUEST = 'HOMEPAGE_GET_ALL_CARDS_REQUEST'
export const HOMEPAGE_GET_ALL_CARDS_SUCCESS = 'HOMEPAGE_GET_ALL_CARDS_SUCCESS'
export const HOMEPAGE_GET_ALL_CARDS_FAIL = 'HOMEPAGE_GET_ALL_CARDS_FAIL'